version: '3.8'

services:
  # Сервис базы данных
  db:
    image: postgres:16
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data # Сохраняем данные при перезапуске
    env_file:
      - .env

  # Приложение
  app:
    build: .
    restart: always
    ports:
      - "8000:8000" # Проброс порта наружу
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./static/stickers:/app/static/stickers
      - ./static/uploads/items:/app/static/uploads/items

# Объявляем том для хранения данных БД
volumes:
  postgres_data:
